name: dockerize-app
run-name: Dockerizing the interview app
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to JFrog
        uses: docker/login-action@v2
        with:
          registry: delizardo.jfrog.io
          username: ${{ secrets.LENDBUZZ_USER }}
          password: ${{ secrets.LENDBUZZ }}
      - name: Build and push
        id: docker_interview_app_image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: delizardo.jfrog.io/interview-app:latest
