name: dockerize-app
run-name: Dockerizing the interview app
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building interview app docker image
        run: docker build . --file Dockerfile --tag interview-app:$(date +%s)
