name: dockerize-app
run-name: Dockerizing the interview app
on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"
jobs:
  buildpush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to JFrog
        uses: docker/login-action@v2
        with:
          registry: delizardo.jfrog.io
          username: ${{ secrets.LENDBUZZ_USER }}
          password: ${{ secrets.LENDBUZZ_PASS }}
      - name: Build and publish to registry
        run: |
          docker build . --file Dockerfile --tag interview-app:$(date +%s)
          docker push interview-app-local/interview-app:$(date +%s)
